application: shapedkite
version: 1-1-0
runtime: python27
api_version: 1
threadsafe: true

handlers:
# main webpage handler
- url: /
  static_files: index.html
  upload: index.html

- url: /index\.html
  static_files: index.html
  upload: index.html

- url: /about
  static_files: about.html
  upload: about.html


# resources handlers
- url: /styles/(.*\.(less|css|eot|otf|svg|ttf|woff|woff2))$
  static_files: styles/\1
  upload: styles/(.*\.(less|css|eot|otf|svg|ttf|woff|woff2))$

- url: /scripts/(src|dict)/(.*\.(js|coffee))$
  static_files: lib/\1/\2
  upload: lib/(.*?)/(.*\.(js|coffee))$

- url: /fonts/(.*\.(ttf))$
  static_files: fonts/\1
  upload: fonts/(.*\.(ttf))$

# templates
- url: /templates/(src|dict)/(.*\.(js|coffee))$
  static_files: templates/\1/\2
  upload: templates/(.*?)/(.*\.(js|coffee))$

# images
- url: /images/(.*\.(ico|png|jpg|jpeg))$
  static_files: img/\1
  upload: img/(.*\.(ico|png|jpg|jpeg))$


skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$


libraries:
- name: webapp2
  version: latest
